let cantons = [
    {
        id: 'CH',
        name: 'Schweiz / Suisse / Svizzera / Svizra'
    }, {
        id: 'AG',
        name: 'Aargau',
        offsetX: 0,
        offsetY: 0,
    }, {
        id: 'AI',
        name: 'Appenzell Innerrhoden',
        offsetX: 0,
        offsetY: 5,
    }, {
        id: 'AR',
        name: 'Appenzell Ausserrhoden',
        offsetX: 0,
        offsetY: -10,
    }, {
        id: 'BE',
        name: 'Bern',
        offsetX: 0,
        offsetY: 0,
    }, {
        id: 'BL',
        name: 'Basel-Landschaft',
        offsetX: 0,
        offsetY: 0,
    }, {
        id: 'BS',
        name: 'Basel-Stadt',
        offsetX: 0,
        offsetY: 0,
    }, {
        id: 'FR',
        name: 'Fribourg',
        offsetX: 0,
        offsetY: 0,
    }, {
        id: 'GE',
        name: 'Genève',
        offsetX: 0,
        offsetY: 0,
    }, {
        id: 'GL',
        name: 'Glarus',
        offsetX: 0,
        offsetY: 0,
    }, {
        id: 'GR',
        name: 'Grischun',
        offsetX: 0,
        offsetY: 0,
    }, {
        id: 'JU',
        name: 'Jura',
        offsetX: 0,
        offsetY: 0,
    }, {
        id: 'LU',
        name: 'Luzern',
        offsetX: 0,
        offsetY: 0,
    }, {
        id: 'NE',
        name: 'Neuchâtel',
        offsetX: 0,
        offsetY: 0,
    }, {
        id: 'NW',
        name: 'Nidwalden',
        offsetX: 0,
        offsetY: -10,
    }, {
        id: 'OW',
        name: 'Obwalden',
        offsetX: 0,
        offsetY: 10,
    }, {
        id: 'SG',
        name: 'St. Gallen',
        offsetX: 0,
        offsetY: 0,
    }, {
        id: 'SH',
        name: 'Schaffhausen',
        offsetX: -10,
        offsetY: -10,
    }, {
        id: 'SO',
        name: 'Solothurn',
        offsetX: 0,
        offsetY: 0,
    }, {
        id: 'SZ',
        name: 'Schwyz',
        offsetX: 0,
        offsetY: 0,
    }, {
        id: 'TG',
        name: 'Thurgau',
        offsetX: 0,
        offsetY: 0,
    }, {
        id: 'TI',
        name: 'Ticino',
        offsetX: 0,
        offsetY: 0,
    }, {
        id: 'UR',
        name: 'Uri',
        offsetX: 0,
        offsetY: 0,
    }, {
        id: 'VD',
        name: 'Vaud',
        offsetX: 0,
        offsetY: 0,
    }, {
        id: 'VS',
        name: 'Valais',
        offsetX: 0,
        offsetY: 0,
    }, {
        id: 'ZG',
        name: 'Zug',
        offsetX: 0,
        offsetY: 0,
    }, {
        id: 'ZH',
        name: 'Zürich',
        offsetX: 0,
        offsetY: 0,
    }
]

export { cantons }